--- # Default tracker configuration
global:
  log:
    verbose: true # true - verbose, false - not verbose, null - middle

Bluetooth:
  - name: Tracker-1
    dev: hci0 # Bluetooth device name
    enabled: true # Up & running
    visible: true # Visible to device scan
    encrypt: true # Encrypt bluetooth link
    pin: null # PIN-code for pairing (up to 16 symbols) - will be generated if not set
    afh: true # Adaptive Frequency Hopping - to reduce interference with other wireless
    signals: # Used in the code to execute the remote module function
      audio_switch:
        instance: GPIO
        socket: audioSwitch

GPIO:
  - name: GPIO
    enabled: true

    sockets: # Sockets is used to automatically generate functions that required by signals
      celluralPowerSwitch: # DIYMall 3G/GPS module 5320_ON/OFF pin
        type: switch
        pin: 13 # GPIO27
      audioSwitch: # Custom pin, connected to modified DELCO radio
        type: switch
        pin: 37 # GPIO26

    listen: # It can listen gpio ports and do some actions when port is changed
      ignition:
        pin: 35 # GPIO19
        signals:
          - socket: disableUSB # Disable LAN & USB
            module: Power
            when: false
          - socket: disableBluetooth # Disable Bluetooth
            module: Bluetooth
            when: false
          - socket: switchClient # Switch WiFi to client mode
            module: WiFi
            when: false
          - socket: disableCelluralOnConnected # Disable Cellural if WiFi found
            module: WiFi
            when: false

          - socket: enableUSB # Enable LAN & USB
            module: Power
            when: true
          - socket: enableBluetooth # Enable Bluetooth
            module: Bluetooth
            when: true
          - socket: switchAdHoc # Switch WiFi to ad-hoc mode
            module: WiFi
            when: true
          - socket: start # Enable Cellural
            module: Cellural
            when: true

Cellural:
  - name: GSMGPS
    enabled: false
    dev: /dev/ttyS0
    net:
      enabled: true
      apn: Phone # AT&T apn for 3G
      user: null # User auth for the APN
      pass: null # Password auth for the APN
    gps:
      enabled: true
      agps: supl.google.com:7276 # Assistant-GPS url
    signals:
      power:
        instance: GPIO
        socket: celluralPower

ALDL160:
  - name: ALDL 160 baud
    enabled: true
    dev: /dev/ttyUSB0
